name: Keep Streamlit App Alive

on:
  schedule:
    # Run once daily at 00:00 UTC (adjust time as needed)
    - cron: "0 0 * * *"

  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  ping_app:
    runs-on: ubuntu-latest

    steps:
    - name: Send GET request to keep app alive
      run: |
        curl -X GET "https://your-streamlit-app-url.com"
