name: Keep Streamlit App Alive

on:
  schedule:
    # Run once daily at 00:00 UTC
    - cron: "0 0,12 * * *"

  workflow_dispatch: # Allows manual triggering of the workflow
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update_date_and_ping_app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Update date in Streamlit app
      run: |
        current_date=$(date '+%Y-%m-%d-%h')
        sed -i "s/st.text(\"Today is .*\")/st.text(\"Today is $current_date\")/" workouts.py

    - name: Commit and push changes
      run: |
        git config --local user.name "github-actions"
        git config --local user.email "github-actions@github.com"
        git add workouts.py
        git commit -m "Update date in Streamlit app to $current_date"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send GET request to keep app alive
      run: |
        curl -X GET "https://barabod.streamlit.app"
